# Generated by Django 5.2 on 2025-04-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed_sold', 'Confirmed Sold'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
