# Generated by Django 5.2 on 2025-04-28 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_latitude_shop_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(default=False, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')]),
        ),
    ]
